version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./static:/usr/share/nginx/html:ro
    networks:
      - traefik
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx.rule=Host(`recollector.ozeliurs.com`)"
        - "traefik.http.routers.nginx.entrypoints=websecure"
        - "traefik.http.routers.nginx.tls=true"
        - "traefik.http.routers.nginx.tls.certresolver=cloudflare"
        - "traefik.http.services.nginx.loadbalancer.server.port=80"

networks:
  traefik:
    external: true